#!/usr/bin/env sh

readonly ACTION=$1

if [ "" == "$(readlink $0)" ]; then
    readonly KATA_INCLUDE=$(dirname $0)
else
    readonly KATA_INCLUDE=$(dirname $(readlink $0))
fi

source $KATA_INCLUDE/utils


function banner() {
    echo "\033[0;33mCode Kata.\033[0m Programming for education and fun"
}

function setup_environment() {
    set -e

    if [ ! -n "$KATA" ]; then
	readonly KATA=~/.codekata
    fi
}

function do_action() {
    local kata_path=$1
    local action=$2
    
    if [ ! -z "$action" ]; then
	if [ -e "$kata_path/scripts/$action" ]; then
	    "$kata_path/scripts/$action"
	else
	    if [ -e $kata_path/recipes/$action.sh ]; then
		sh $kata_path/recipes/$action.sh
	    else
		echo "Unknown or missing action"
	    fi
	fi
    fi
}



banner
setup_environment
do_action $KATA $ACTION
