#!/usr/bin/env bash

shopt -s extglob
set -o errtrace
set -o errexit

codekata_install_initialize()
{
  DEFAULT_SOURCES=(github.com/grahambrooks/codekata)

  BASH_MIN_VERSION="3.2.25"
  if
    [[ -n "${BASH_VERSION:-}" &&
      "$(\printf "%b" "${BASH_VERSION:-}\n${BASH_MIN_VERSION}\n" | LC_ALL=C \sort -n -t"." | \head -n1)" != "${BASH_MIN_VERSION}"
    ]]
  then
    echo "BASH ${BASH_MIN_VERSION} required (you have $BASH_VERSION)"
    exit 1
  fi

  export HOME PS4
  export codekata_trace_flag codekata_debug_flag codekata_user_install_flag codekata_ignore_codekatarc codekata_prefix codekata_path

  PS4="+ \${BASH_SOURCE##\${codekata_path:-}} : \${FUNCNAME[0]:+\${FUNCNAME[0]}()}  \${LINENO} > "
}

log()  { printf "%b\n" "$*"; }
debug(){ [[ ${codekata_debug_flag:-0} -eq 0 ]] || printf "Running($#): $*"; }
fail() { log "\nERROR: $*\n" ; exit 1 ; }

codekata_install()
{
  codekata_install_initialize
}

codekata_install "$@"
