.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH "Prime Facotrs" "Code Kata"
.SH SYNOPSIS

Originally developed by Robert Marting (Uncle Bob)

This is a fun kata

.SH PLAY

Write a static method generate() that given an integer N will return a
list of integers such that the numbers are the factors of N and are
arranged in increasing numerical order. generate(1) should return an
empty list. generate(30) should return the numbers 2,3,5.

.SH VARIATIONS

